#+TITLE: Amazed Documentation
#+AUTHOR: Matthijs de Vries and Elsa Carlsson
#+OPTIONS: TOC:nil ':t

* Data structures
The frontier stack is entirely local; every thread is searching through one part of the maze independently. Therefore it can continue to simply be a ~Stack~.

To prevent multiple threads from visited the same node, the visited-set must be shared. The most natural choice for this is ~java.util.concurrent.ConcurrentSkipListSet~.

The predecessor-map does not need to be shared but needs to be inherited by child threads as they need to know how their parent got to where they start.

* Algorithm
+ Start by pushing the start node onto the frontier stack.
+ Until the frontier becomes empty:
  + Pop a "current" node from the frontier
  + Try to visit the current node, else continue loop
  + If current is a goal:
    + Set termination flag
    + Return the found path
  + Otherwise, loop through all neighbors:
    + If termination flag is set, break out of (inner) loop
    + If this neighbor is already in the predecessor map, continue (inner) loop
    + Update predecessor map
    + Either: fork a child
    + Or: push to frontier
  + If termination flag is set, break out of loop
+ Loop through all children:
  + Join the child and look at its result
  + If it found a path, return that
+ return null

# Trying to visit a node
# Termination flag
# Forking decision
# Forking

* Synchronization
The threads are synchronized using two objects: the visited-map and the termination flag. These are a ~java.util.concurrent.ConcurrentSkipListSet~ and a ~java.util.concurrent.atomic.AtomicBoolean~ respectively.

These classes are lock-free, and since we don't use any other synchronization our search is also lock-free.

There is no data races when we use ~ConcurrentSkipListSet~ because each thread checks if a node is free and takes control of it in a single atomic operation, using ~visited.add(current)~ (and checking the return value).

And there is no data races in our use of ~AtomicBoolean~ either, because we never rely on the timing on when this is set. It starts of false and is eventually set to true, and all threads will eventually check it and see the new value.

* --- :noexport:

#+BEGIN_SRC java
        int count = 0;
        int player = maze.newPlayer(start);
        frontier.push(start);

        while (!frontier.empty()) {
            int current = frontier.pop();

            if (visited.add(current)) { // "true if this set did not already contain the specified element"
                maze.move(player, current);

                if (maze.hasGoal(current)) {
                    shutdown.set(true);
                    return pathFromTo(maze.start(), current);
                }

                for (int nb: maze.neighbors(current)) {
                    if (shutdown.get()) {
                        break;
                    }

                    predecessor.put(nb, current);

                    if (count >= forkAfter /*should fork?*/) {
                        ForkJoinSolver child = new ForkJoinSolver(maze, visited, predecessor, nb, shutdown, forkAfter);
                        children.add(child);
                        child.fork();
                        count = 0;
                    } else {
                        frontier.push(nb);
                        count++;
                    }
                }
            }
            if (shutdown.get()) {
                break;
            }
        }
        // all nodes explored, wait for children
        for (ForkJoinSolver child : children) {
            List<Integer> result = child.join();
            if (result != null) {
                return result;
            }
        }
        // no goal found
        return null;
    }
#+END_SRC

Starting with the shared resources we realized that the visited set has to be a shared resource and thus thread safe
this was easliy done by using the ConcurrentSkipList class. the frontier stack is completely local and the predecessors 
are all merged together when the forks join back together. For our solution we made an additional constructor taking all variables. 
In the ParallelSearch method we basically followed the instructions given to us. We pop a node from frontiers. Check that it's not empty, 
'check if it has been visited, if not add the node to the visited set and move the player, if the goal has been found we use the pathFromTo given to us.
To make sure all forks stop we introduced a global flag (included in the constructor) which is set to true when a goal has been found 
or when all nodes have been explored. once on a node, each neighbour is checked. this is where we fork using the forkAfter variable and a simple counter 
to keep track of when to fork. When all nodes are explored we join together all forks and return the result or null if no goal was found.


from requirements:

discuss race condition and data races

discuss lock-free(ness)
